default: &defaults
  parallelism: 1
  working_directory: ~/repo
  docker:
    - image: circleci/node:6-browsers
  dependencies:
    cache_directories:
     - ~/nvm

restore_npm_cache: &restore_npm_cache
  restore_cache:
    keys:
      - SerenityJS-Cucumber-Protractor-StandAlone-{{ .Branch }}-{{ checksum "package.json" }}
      - SerenityJS-Cucumber-Protractor-StandAlone-{{ .Branch }}-

save_npm_cache: &save_npm_cache
  save_cache:
    key: SerenityJS-Cucumber-Protractor-StandAlone-{{ .Branch }}-{{ checksum "package.json" }}
    paths:
      # - ~/.cache/npm
      - "node_modules"

install_depencies_with_npm: &install_depencies_with_npm
  run:
    name: Npm Install
    command: cd serenity-develop && npm install

run_tests: &run_tests
  run:
    name: Run Tests
    command: |
      cd serenity-develop && npm run test
version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_npm_cache
      - *install_depencies_with_npm
      - *save_npm_cache
      - *run_tests

workflows:
  version: 2
  build-and-test:
    jobs:
- test
